# Generated by Django 5.0.6 on 2024-11-25 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.JSONField(default=list)),
                ('columnIndex', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('imgURL', models.CharField(blank=True, max_length=100, null=True)),
                ('workSpaceMemberOrder', models.JSONField(blank=True, default=list, null=True)),
                ('workSpaceOwnerOrder', models.JSONField(blank=True, default=list, null=True)),
                ('workSpaceRequest', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardIndex', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('dueDate', models.DateTimeField()),
                ('task', models.JSONField(blank=True, default=list, null=True)),
                ('columnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.column')),
                ('assignID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='workSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('members', models.JSONField(blank=True, default=list, null=True)),
                ('icon_unified', models.CharField(max_length=100)),
                ('request', models.JSONField(blank=True, default=list, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='workSpaceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.workspace'),
        ),
    ]
